config/routes.rb
Rails.application.routes.draw do
  resources :sondes
  root to: 'etalons#index'


  resources :etalons
  resources :marques
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/etalon.rb
class Etalon < ApplicationRecord
  belongs_to :marque
  has_many :sondes
  
  def liste_etalons_mis_en_forme
	"#{modele} n°#{serie}"
  end
end

app/models/marque.rb
class Marque < ApplicationRecord
  has_many :etalons
end

app/models/sonde.rb
class Sonde < ApplicationRecord
  belongs_to :etalon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/etalons_controller.rb
class EtalonsController < ApplicationController
  before_action :set_etalon, only: [:show, :edit, :update, :destroy]
  before_action :set_marques, only: [:new, :edit]

  # GET /etalons
  # GET /etalons.json
  def index
    @etalons = Etalon.all.includes(:marque, :sondes)
  end

  # GET /etalons/1
  # GET /etalons/1.json
  def show
  end

  # GET /etalons/new
  def new
    @etalon = Etalon.new
  end

  # GET /etalons/1/edit
  def edit
  end

  # POST /etalons
  # POST /etalons.json
  def create
    @etalon = Etalon.new(etalon_params)

    respond_to do |format|
      if @etalon.save
        format.html { redirect_to @etalon, notice: 'L\'Etalon a été créé avec succès.' }
        format.json { render :show, status: :created, location: @etalon }
      else
        format.html { render :new }
        format.json { render json: @etalon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etalons/1
  # PATCH/PUT /etalons/1.json
  def update
    respond_to do |format|
      if @etalon.update(etalon_params)
        format.html { redirect_to @etalon, notice: 'L\'Etalon a été mis à jour avec succès.' }
        format.json { render :show, status: :ok, location: @etalon }
      else
        format.html { render :edit }
        format.json { render json: @etalon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etalons/1
  # DELETE /etalons/1.json
  def destroy
    @etalon.destroy
    respond_to do |format|
      format.html { redirect_to etalons_url, notice: 'L\'Etalon a été supprimé avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etalon
      @etalon = Etalon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def etalon_params
      params.require(:etalon).permit(:serie, :modele, :marque_id)
    end
	
	def set_marques
	  @marques = Marque.all
	end
end

app/controllers/marques_controller.rb
class MarquesController < ApplicationController
  before_action :set_marque, only: [:show, :edit, :update, :destroy]

  # GET /marques
  # GET /marques.json
  def index
    @marques = Marque.all
  end

  # GET /marques/1
  # GET /marques/1.json
  def show
  end

  # GET /marques/new
  def new
    @marque = Marque.new
  end

  # GET /marques/1/edit
  def edit
  end

  # POST /marques
  # POST /marques.json
  def create
    @marque = Marque.new(marque_params)

    respond_to do |format|
      if @marque.save
        format.html { redirect_to @marque, notice: 'La Marque a été ajoutée avec succès.' }
        format.json { render :show, status: :created, location: @marque }
      else
        format.html { render :new }
        format.json { render json: @marque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marques/1
  # PATCH/PUT /marques/1.json
  def update
    respond_to do |format|
      if @marque.update(marque_params)
        format.html { redirect_to @marque, notice: 'La Marque a été mise à jour avec succès.' }
        format.json { render :show, status: :ok, location: @marque }
      else
        format.html { render :edit }
        format.json { render json: @marque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marques/1
  # DELETE /marques/1.json
  def destroy
    @marque.destroy
    respond_to do |format|
      format.html { redirect_to marques_url, notice: 'La Marque a été supprimée avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marque
      @marque = Marque.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marque_params
      params.require(:marque).permit(:name)
    end
end

app/controllers/sondes_controller.rb
class SondesController < ApplicationController
  before_action :set_sonde, only: [:show, :edit, :update, :destroy]
  before_action :set_etalons, only: [:new, :edit, :update]

  # GET /sondes
  # GET /sondes.json
  def index
    @sondes = Sonde.all.includes(:etalon)
  end

  # GET /sondes/1
  # GET /sondes/1.json
  def show
  end

  # GET /sondes/new
  def new
    @sonde = Sonde.new
  end

  # GET /sondes/1/edit
  def edit
  end

  # POST /sondes
  # POST /sondes.json
  def create
    @sonde = Sonde.new(sonde_params)

    respond_to do |format|
      if @sonde.save
        format.html { redirect_to @sonde, notice: 'La Sonde a été créée avec succès.' }
        format.json { render :show, status: :created, location: @sonde }
      else
        format.html { render :new }
        format.json { render json: @sonde.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sondes/1
  # PATCH/PUT /sondes/1.json
  def update
    respond_to do |format|
      if @sonde.update(sonde_params)
        format.html { redirect_to @sonde, notice: 'La Sonde a été mise à jour avec succès' }
        format.json { render :show, status: :ok, location: @sonde }
      else
        format.html { render :edit }
        format.json { render json: @sonde.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sondes/1
  # DELETE /sondes/1.json
  def destroy
    @sonde.destroy
    respond_to do |format|
      format.html { redirect_to sondes_url, notice: 'La Sonde a été supprimée avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sonde
      @sonde = Sonde.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sonde_params
      params.require(:sonde).permit(:serie, :modele, :etalon_id)
    end
	
	def set_etalons
		@etalons = Etalon.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/etalons_helper.rb
module EtalonsHelper
end

app/helpers/marques_helper.rb
module MarquesHelper
end

app/helpers/sondes_helper.rb
module SondesHelper
end

app/views/etalons/_form.html.erb
<%= form_for(etalon) do |f| %>
  <div class="form-group">
    <%= f.label :serie, 'Numéro de Série' %>
    <%= f.text_field :serie %>
  </div>

  <div class="form-group">
    <%= f.label :modele, 'Modèle' %>
    <%= f.text_field :modele %>
  </div>
  
  <div class="form-group">
    <%= f.label :marque_id, 'Marque' %>
    <%= f.select(:marque_id, options_from_collection_for_select(@marques, :id, :name)) %>
  </div>

  <%= f.submit :value => 'Enregistrer', :class => 'btn btn-default' %>
<% end %>

app/views/etalons/edit.html.erb
<h1>Modifier Etalon</h1>

<%= render 'form', etalon: @etalon %>

<%= link_to 'Afficher', @etalon %> |
<%= link_to 'Retour', etalons_path %>

app/views/etalons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Etalons</h1>

<table class="table table-hover">
  <thead>
    <tr>
	  <th>Modele</th>
      <th>N° de Série</th>
	  <th>Marque</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @etalons.each do |etalon| %>
      <tr class="success">
	    <td class="col-md-3"><%= etalon.modele %></td>
        <td class="col-md-3"><%= etalon.serie %></td>
		<td class="col-md-3"><%= etalon.marque.name %></td>
        
        <td class="col-md-1"><%= link_to 'Afficher', etalon %></td>
        <td class="col-md-1"><%= link_to 'Modifier', edit_etalon_path(etalon) %></td>
        <td class="col-md-1"><%= link_to 'Supprimer', etalon, method: :delete, data: { confirm: 'Êtes-vous sûr?' } %></td>
      </tr>
	  <% etalon.sondes.each do|sonde|%>
	    <tr class="info">
	      <td class="col-md-3">&nbsp;&nbsp;<%= sonde.modele %></td>
		  <td class="col-md-3"><%= sonde.serie %></td>
		  <td class="col-md-3"></td>
		  
		  <td class="col-md-1"><%= link_to 'Afficher', sonde %></td>
          <td class="col-md-1"><%= link_to 'Modifier', edit_sonde_path(sonde) %></td>
          <td class="col-md-1"><%= link_to 'Supprimer', sonde, method: :delete, data: { confirm: 'Êtes-vous sûr?' } %></td>
	    </tr>
	  <% end %>
    <% end %>
  </tbody>
</table>
<% puts @etalons.inspect %>
<br>

<%= link_to 'Ajouter Etalon', new_etalon_path %>

app/views/etalons/new.html.erb
<h1>Ajouter Etalon</h1>

<%= render 'form', etalon: @etalon %>

<%= link_to 'Retour', etalons_path %>

app/views/etalons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numéro de Série:</strong>
  <%= @etalon.serie %>
</p>

<p>
  <strong>Modèle:</strong>
  <%= @etalon.modele %>
</p>

<p>
  <strong>Marque:</strong>
  <%= @etalon.marque.name %>
</p>
<%= link_to 'Modifier', edit_etalon_path(@etalon) %> |
<%= link_to 'Retour', etalons_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <h5 class="h5">Planète Médicale 2017</h1>
</footer>

app/views/layouts/_menu.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
	<%= link_to "Parc Etalons", '#', id: "logo" %>
	<nav>
	  <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Etalons', etalons_path %></li>
		<li><%= link_to 'Sondes', sondes_path %></li>
	    <li><%= link_to 'Marques', marques_path %></li>
	  </ul>
	  </nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParcEtalons</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application.scss', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default.coffee', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render 'layouts/menu' %>
	<div class="container">
      <%= yield %>
	</div>
	<%= render 'layouts/footer' %>
  </body>
</html>

app/views/marques/_form.html.erb
<%= form_for(marque) do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nom' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <%= f.submit :value => 'Enregistrer', :class => 'btn btn-default' %>
<% end %>

app/views/marques/edit.html.erb
<h1>Editing Marque</h1>

<%= render 'form', marque: @marque %>

<%= link_to 'Afficher', @marque %> |
<%= link_to 'Retour', marques_path %>

app/views/marques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marques</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marques.each do |marque| %>
      <tr>
        <td class="col-md-9"><%= marque.name %></td>
        <td class="col-md-1"><%= link_to 'Afficher', marque %></td>
        <td class="col-md-1"><%= link_to 'Modifier', edit_marque_path(marque) %></td>
        <td class="col-md-1"><%= link_to 'Supprimer', marque, method: :delete, data: { confirm: 'Êtes-vous sûr?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajouter Marque', new_marque_path %>

app/views/marques/new.html.erb
<h1>Ajouter Marque</h1>

<%= render 'form', marque: @marque %>

<%= link_to 'Retour', marques_path %>

app/views/marques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @marque.name %>
</p>

<%= link_to 'Modifier', edit_marque_path(@marque) %> |
<%= link_to 'Retour', marques_path %>

app/views/sondes/_form.html.erb
<%= form_for(sonde) do |f| %>
  <div class="form-group">
    <%= f.label :serie, "Numéro de série" %>
    <%= f.text_field :serie %>
  </div>

  <div class="form-group">
    <%= f.label :modele, "Modèle" %>
    <%= f.text_field :modele %>
  </div>
  
  <div class="form-group">
    <%= f.label :etalon_id, 'Etalons' %>
    <%= f.select(:etalon_id, options_from_collection_for_select(@etalons, :id, :liste_etalons_mis_en_forme)) %>
  </div>

  <%= f.submit :value => 'Enregistrer', :class => 'btn btn-default' %>
<% end %>

app/views/sondes/edit.html.erb
<h1>Modifier Sonde</h1>

<%= render 'form', sonde: @sonde %>

<%= link_to 'Afficher', @sonde %> |
<%= link_to 'Retour', sondes_path %>

app/views/sondes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sondes</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>N° de série</th>
      <th>Modèle</th>
	  <th>Etalon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sondes.each do |sonde| %>
      <tr>
        <td class="col-md-2"><%= sonde.serie %></td>
        <td class="col-md-2"><%= sonde.modele %></td>
		<td class="col-md-5"><%= "#{sonde.etalon.modele} n°#{sonde.etalon.serie}" %></td>
		
        <td class="col-md-1"><%= link_to 'Show', sonde %></td>
        <td class="col-md-1"><%= link_to 'Edit', edit_sonde_path(sonde) %></td>
        <td class="col-md-1"><%= link_to 'Destroy', sonde, method: :delete, data: { confirm: 'Êtes-vous sûr?' } %></td>


	  </tr>
    <% end %>
  </tbody>
</table>
<% puts @sondes.inspect %>
<br>

<%= link_to 'Ajouter sonde', new_sonde_path %>

app/views/sondes/new.html.erb
<h1>New Sonde</h1>

<%= render 'form', sonde: @sonde %>

<%= link_to 'Retour', sondes_path %>

app/views/sondes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numéro de série:</strong>
  <%= @sonde.serie %>
</p>

<p>
  <strong>Modèle:</strong>
  <%= @sonde.modele %>
</p>

<%= link_to 'Modifier', edit_sonde_path(@sonde) %> |
<%= link_to 'Retour', sondes_path %>